#!/bin/sh

# Install Mackup with PIP
if which pip 2>&1 > /dev/null; then
	pip install --upgrade mackup
else
	pip3 install --upgrade mackup
fi

# install ohmybash
bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" > /dev/null

# install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
if [ -d $HOME/linuxbrew ]; then
	eval "$($HOME/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

# install earhly ci
mkdir -p "$HOME/.local/bin"
wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O $HOME/.local/bin/earthly && \
chmod +x $HOME/.local/bin/earthly && \
$HOME/.local/bin/earthly bootstrap --with-autocomplete;


# install go
brew install go

# setup nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
nvm install 17.7.1
nvm install 16.14.0

# install pyenv
git clone https://github.com/pyenv/pyenv.git ~/.pyenv

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

pyenv install 3.8.9
pyenv install 3.9.0

# install deno
curl -fsSL https://deno.land/x/install/install.sh | sh

# install github sync
git clone https://github.com/oxzi/github-orga-sync ~/.github-org-sync && cd ~/.github-org-sync && go install && cd -

# install rbenv
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
cd ~/.rbenv && src/configure && make -C src && cd -
~/.rbenv/bin/rbenv init


# install sdkman
curl -s "https://get.sdkman.io" | bash
echo 'source "$HOME/.sdkman/bin/sdkman-init.sh"' > ~/.profile
source "$HOME/.sdkman/bin/sdkman-init.sh"

# install rustlang
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# install solana
sh -c "$(curl -sSfL https://release.solana.com/v1.9.2/install)"

# setup yay
git clone https://aur.archlinux.org/yay.git ~/bin/yay

echo 'source $HOME/dotfiles/Mackup/config' >> $HOME/.profile
